map_type: costmap

obstacle_range: 5.0 #1.5
raytrace_range: 8.0 #4.0

transform_tolerance: 1.25

robot_radius: 0.40

inflation_radius: 0.55 #was 0.65

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: sagar_bot/laser/scan, marking: true, clearing: true}
